# Generated by Django 4.0 on 2022-01-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='has_unread',
        ),
    ]
