# Generated by Django 4.0 on 2022-01-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_profile_friends_alter_profile_image'),
        ('posts', '0003_remove_messagemodel_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='social.profile'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='social.profile'),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadreceiver', to='social.profile'),
        ),
    ]
